Fix for missing default priority setting
akusei/pushover-bash pull request #8
Opened 2021-11-24 15:33 UTC by silviuvulcan

Unless testing for this I get the following error if I don't define a `priority=` in pushover-config

```bash
$ pushover.sh -m "Test"
/home/user/bin/pushover.sh: line 178: [: -eq: unary operator expected
$
```

Thanks for the script, I use it all the time!

2021-11-24 15:54 UTC, silviuvulcan commented
I also added -H and -M options for monospaced and html formatting.

2021-12-01 21:08 UTC, akusei requested changes

2021-12-01 21:08 UTC, akusei commented on pushover.sh
> +  if [ $priority -eq 2 ]; then
I'm not able to test this at the moment but it might be better to do this instead of adding another layer of nested IFs

`if [ ${priority:-0} -eq 2 ]; then`

2022-01-02 20:15 UTC, akusei commented
Closing this out as the OP has not responded or made the requested changes. I've recreated these changes with some other small improvements in #9

2022-01-02 20:15 UTC, closed without merging

2022-01-03 14:47 UTC, silviuvulcan commented
Sorry. Meant to reply and forogot :( happy it's fixed.